apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hello-world-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: fkcurrie/hello-world-3
      ephemeral: true
      labels:
        - self-hosted
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      initContainers:
      - name: init
        image: busybox
        command: ['sh', '-c', 'sleep 10']
      dockerdWithinRunnerContainer: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
